# -*- coding: utf-8 -*-
"""task 2 .1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xpSxm3q8L42zLMxtpYK9ZYW30I0KioM
"""

!pip install beautifulsoup4 requests

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://quotes.toscrape.com"
response = requests.get(url)
print("Status Code:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

quotes = soup.find_all("span", class_="text")
authors = soup.find_all("small", class_="author")
quote_list = []
author_list = []
for q, a in zip(quotes, authors):
    quote_list.append(q.text)
    author_list.append(a.text)

data = {
    "Quote": quote_list,
    "Author": author_list
}
df = pd.DataFrame(data)
df

from google.colab import files
df.to_csv('quotes_scraped.csv', index=False)
files.download("quotes_scraped.csv")